const ActionType = {
  //GET FOTO
  GET_FOTO_RESTO_MENUS: "GET_FOTO_RESTO_MENUS",
  GET_FOTO_RESTO_MENUS_SUCCEED: "GET_FOTO_RESTO_MENUS_SUCCEED",
  GET_FOTO_RESTO_MENUS_FAILED: "GET_FOTO_RESTO_MENUS_FAILED",

  //UPDATE FOTO
  UPDATE_FOTO_RESTO_MENUS: "UPDATE_UPDATE_FOTO_RESTO_MENUS",
  UPDATE_FOTO_RESTO_MENUS_SUCCEED: "UPDATE_UPDATE_FOTO_RESTO_MENUS_SUCCEED",
  UPDATE_FOTO_RESTO_MENUS_FAILED: "UPDATE_UPDATE_FOTO_RESTO_MENUS_FAILED",

  //CREATE FOTO
  ADD_FOTO_RESTO_MENUS: "ADD_FOTO_RESTO_MENUS",
  ADD_FOTO_RESTO_MENUS_SUCCEED: "ADD_FOTO_RESTO_MENUS_SUCCED",
  ADD_FOTO_RESTO_MENUS_FAILED: "ADD_FOTO_RESTO_MENUS_FAILED",

  // GET CARD ALL CLIENT
  GET_CARDRESTOMENUS: "GET_CARDRESTOMENUS",
  GET_CARDRESTOMENUS_SUCCEED: "GET_CARDRESTOMENUS_SUCCEED",
  GET_CARDRESTOMENUS_FAILED: "GET_CARDRESTOMENUS_FAILED",

  // Get Tabel Resto Menus
  GET_RESTOMENUS: "GET_RESTOMENUS",
  GET_RESTOMENUS_SUCCEED: "GET_RESTOMENUS_SUCCEED",
  GET_RESTOMENUS_FAILED: "GET_RESTOMENUS_FAILED",

  // Update Tabel Resto Menus
  UPDATE_RESTOMENUS: "UPDATE_RESTOMENUS",
  UPDATE_RESTOMENUS_SUCCEED: "UPDATE_RESTOMENUS_SUCCEED",
  UPDATE_RESTOMENUS_FAILED: "UPDATE_RESTOMENUS_FAILED",

  // Create Tabel Resto Menus
  ADD_RESTOMENUS: "ADD_RESTOMENUS",
  ADD_RESTOMENUS_SUCCEED: "ADD_RESTOMENUS_SUCCEED",
  ADD_RESTOMENUS_FAILED: "ADD_RESTOMENUS_FAILED",

  // Delete Tabel Resto Menus
  DEL_RESTOMENUS: "DEL_RESTOMENUS",
  DEL_RESTOMENUS_SUCCEED: "DEL_RESTOMENUS_SUCCEED",
  DEL_RESTOMENUS_FAILED: "DEL_RESTOMENUS_FAILED",

  // Find One Tabel Resto Menus
  GET_RESTOMENU: "GET_RESTOMENU",
  GET_RESTOMENU_SUCCEED: "GET_RESTOMENU_SUCCEED",
  GET_RESTOMENU_FAILED: "GET_RESTOMENU_FAILED",
  //=============================================================================//
  // Get Tabel Resto Menus Photos
  GET_RESTOMENUS_PHOTOS: "GET_RESTOMENUS_PHOTOS",
  GET_RESTOMENUS_PHOTOS_SUCCEED: "GET_RESTOMENUS_PHOTOS_SUCCEED",
  GET_RESTOMENUS_PHOTOS_FAILED: "GET_RESTOMENUS_PHOTOS_FAILED",

  // Update Tabel Resto Menus Photos
  UPDATE_RESTOMENUS_PHOTOS: "UPDATE_RESTOMENUS_PHOTOS",
  UPDATE_RESTOMENUS_PHOTOS_SUCCEED: "UPDATE_RESTOMENUS_PHOTOS_SUCCEED",
  UPDATE_RESTOMENUS_PHOTOS_FAILED: "UPDATE_RESTOMENUS_PHOTOS_FAILED",

  // Create Tabel Resto Menus Photos
  ADD_RESTOMENUS_PHOTOS: "ADD_RESTOMENUS_PHOTOS",
  ADD_RESTOMENUS_PHOTOS_SUCCEED: "ADD_RESTOMENUS_PHOTOS_SUCCEED",
  ADD_RESTOMENUS_PHOTOS_FAILED: "ADD_RESTOMENUS_PHOTOS_FAILED",

  // Delete Tabel Resto Menus Photos
  DEL_RESTOMENUS_PHOTOS: "DEL_RESTOMENUS_PHOTOS",
  DEL_RESTOMENUS_PHOTOS_SUCCEED: "DEL_RESTOMENUS_PHOTOS_SUCCEED",
  DEL_RESTOMENUS_PHOTOS_FAILED: "DEL_RESTOMENUS_PHOTOS_FAILED",

  // Find One Tabel Resto Menus Photos
  GET_RESTOMENU_PHOTOS: "GET_RESTOMENU_PHOTOS",
  GET_RESTOMENU_PHOTOS_SUCCEED: "GET_RESTOMENU_PHOTOS_SUCCEED",
  GET_RESTOMENU_PHOTOS_FAILED: "GET_RESTOMENU_PHOTOS_FAILED",
};

export default ActionType;
